### ISSUE TITLE
AppBar Component

### ISSUE THREAD

**Issue by kiiiyo** [kiiiyo/media-starter#10]
# Overview

this implementation is AppBar Component.

## TODOs

- [ ] Break point 865px over
    - [ ] Logo and Menus display
- [ ] Break point 864px min
    - [ ] Menu Handler
    - [ ] Menu display
